Feat: post update hook added for booking status & notification
desolintdev/roadtrip2go-shared-resources pull request #1
Opened 2024-10-02 18:47 UTC by syedali042

[Feat: post update hook added for booking status & notification](https://github.com/desolintdev/roadtrip2go-shared-resources/commit/68b935ad3001dd79c58800f744ff9f83af1784d3)

Instead of sending notification mails of booking & updating booking general status in multiple places in code, it's better to do all these things at a single place, so all this process is shifted to mongoose post update hook.

#### commits description

1. [Feat: post update hook added for booking status & notification](https://github.com/desolintdev/roadtrip2go-shared-resources/commit/68b935ad3001dd79c58800f744ff9f83af1784d3)

##### Checklist

- [ ] I have put the Jira ticket number and title in the PR title
- [ ] I have included the Jira ticket link in the PR description
- [ ] I have included a proper description of the changes made in the PR
- [ ] I have included the commit descriptions and links in the PR description
- [ ] I have included the packages changes in the PR description (if applicable)
- [ ] I have tested the changes locally
- [ ] I have tested the changes for responsiveness (if applicable)
- [ ] I have answered responded to all the comments from the Code Rabbit AI
- [ ] I have addressed all the comments of SonarCloud
- [ ] I have addressed all the comments of Socket.dev
- [ ] I have answered responded to all the comments from the reviewers
- [ ] All the comments are resolved

2024-10-02 19:23 UTC, syedali042 commented on constants.js
> +};
Not needed that BOOKING_STATUSES are same as used in other nodeJS apps, so keeping it like is good for consistency.

2024-10-03 12:46 UTC, Amjad992 requested changes

2024-10-03 12:46 UTC, Amjad992 commented on constants.js
> +  failed: {
what's the difference between failed and error?

also don't we have resolved somewhere?

2024-10-03 12:46 UTC, Amjad992 commented on DraftsModel.js
> +  async function updateBookingStatus(doc, newStatus, notificationPath) {
take this function outside the post, no need to decleare it everytime, put it just out and call it

2024-10-03 12:46 UTC, Amjad992 commented on DraftsModel.js
> +      '/bookings/notify/failed'
1) remove this, replace it with typeOfNotificaiton parameters with 2 types, and select the path in the the function. Actually after checking, you don't even need type, you can just cehck the booking status if failed or sucess and notify
2) Convert the function to take object rather than 3 params
3) change the success path to be /booking/notify/success

so you'll just do


    await updateBookingStatus(
      {
      doc,
      BOOKING_STATUSES.failed.value
      }
      }

2024-10-03 15:50 UTC, syedali042 commented on constants.js
> +  failed: {
error is when there is an error while finding rates.

failed is for booking.

2024-10-03 20:28 UTC, Amjad992 approved these changes

2024-10-03 21:20 UTC, merged