IR0-2 - Create Quality Dashboard
desolintdev/roadtrip2go-shared-resources pull request #2
Opened 2024-12-26 19:32 UTC by ahmadZahid99

#### [IR0-2 - Create Quality Dashboard](https://roadtrip2go.atlassian.net/jira/software/c/projects/IR0/boards/4?selectedIssue=IR0-2)

This PR integrates PostHog into the application to track key events in the road trip creation process, including when a trip creation starts (`road_trip_creation_started`), succeeds (`road_trip_creation_success`), fails (`road_trip_creation_failed`), and the time taken for completion (`road_trip_creation_duration`). Each event captures relevant properties such as `booking_id`, `draft_id`, `product_title`, and additional details like the city where a failure occurred or the duration of the process in seconds. This implementation provides valuable insights into user behavior and system performance, aiding in analysis, debugging, and continuous improvement.

#### commits description

1. Add all four events of post hog in shared resources. [6ee1304](https://github.com/desolintdev/roadtrip2go-shared-resources/commit/6ee13044647d92eb239c55d176e66153b5af7dad)

##### Packages Changes

Name: Installed `posthog-js` 
Effect: +19.3 MB to the bundle size

##### Checklist

- [x] I have put the Jira ticket number and title in the PR title
- [x] I have included the Jira ticket link in the PR description
- [x] I have included a proper description of the changes made in the PR
- [x] I have included the commit descriptions and links in the PR description
- [ ] I have included the packages changes in the PR description (if applicable)
- [x] I have tested the changes locally
- [ ] I have tested the changes for responsiveness (if applicable)
- [x] I have answered responded to all the comments from the Code Rabbit AI
- [x] I have addressed all the comments of SonarCloud
- [x] I have addressed all the comments of Socket.dev
- [ ] I have answered responded to all the comments from the reviewers
- [ ] All the comments are resolved

2024-12-26 19:36 UTC, ahmadZahid99 commented on DraftsModel.js
> +}
Thanks for telling me about the tripCreationStartTime

2024-12-26 19:43 UTC, ahmadZahid99 commented on DraftsModel.js
> +        : `${differenceInSeconds.toFixed(2)} seconds`;
Keep it as it is

2024-12-26 19:43 UTC, ahmadZahid99 commented on DraftsModel.js
> +}
thank for this

2024-12-27 08:07 UTC, ahmadZahid99 commented on postHogUtils.js
> +  });
Leave it as it is

2024-12-27 08:08 UTC, ahmadZahid99 commented on postHogUtils.js
> +});
leave it as it is

2024-12-27 08:08 UTC, ahmadZahid99 commented on postHogUtils.js
> +  });
leave it as it is

2024-12-28 11:18 UTC, syedali042 requested changes

2024-12-28 11:18 UTC, syedali042 commented on postHogUtils.js
> +    event: 'road_trip_creation_duration',
Create a postHogConstants file and take this event string from that.

2024-12-30 06:38 UTC, ahmadZahid99 commented on postHogUtils.js
> +    event: 'road_trip_creation_duration',
Done

2024-12-30 18:01 UTC, syedali042 requested changes

2024-12-30 18:01 UTC, syedali042 commented on package.json
> +    "posthog-node": "^4.3.2"
Installation of posthog-node didn't make any change in package-lock.json file???

2024-12-31 07:01 UTC, ahmadZahid99 commented on package.json
> +    "posthog-node": "^4.3.2"
@syedali042 It will be added to the `package-lock.json` file if you install it directly from my branch using this command:  
`npm i desolintdev/roadtrip2go-shared-resources.git#IR0-2-create-quality-dashboard`  
Otherwise, it won't be included.

2024-12-31 08:28 UTC, syedali042 commented on package.json
> +    "posthog-node": "^4.3.2"
Why when you run command of npm i posthog-node, it didn't make any change in package-lock? it doesn't make sense.

2024-12-31 08:31 UTC, ahmadZahid99 commented on package.json
> +    "posthog-node": "^4.3.2"
ok so you are saying when we run this command this will add it in package-lock.json i understand that you are asking when we install this package in the booking engine than is this post hog added in the package-lock file or not

2024-12-31 08:33 UTC, syedali042 commented on package.json
> +    "posthog-node": "^4.3.2"
no this will not add in booking engine lock as it's already added in shared resources.

2024-12-31 08:39 UTC, ahmadZahid99 commented on package.json
> +    "posthog-node": "^4.3.2"
yeah I know but it is added as a dependency of the shared resource otherwise it will not install in the node module and it will be added by the command that I shared before 
![image](https://github.com/user-attachments/assets/d7862795-e6ab-439e-afe2-d7ce2774d085)

2024-12-31 09:54 UTC, syedali042 approved these changes

2024-12-31 11:50 UTC, Amjad992 requested changes

2024-12-31 11:50 UTC, Amjad992 commented on DraftsModel.js
> +    tripCreationStartTime: {
I would sggest to do the following:

timers: {
creationStartTime,
creationEndTime,
recheckRatesStartTime
recheckRatesEndTime
paymentInitializationTime
bookingStartTime
bookingEndTime
}

all the above timestamps can help us later see how much time the user is sending in each step 
e.g. the difference between recheckRatesStartTime and creationEndTime can tell us how much time the user is spending to check accomodation and finally take decision to go with the purchase.
and
e.g. difference between paymentInitializationTime and recheckRatesEndTime can tell us how much time it takes them to click the payment button, which if it was 10 seconds is good, but if it's 30 minutes we'll know the users are wasting time, and in that time we might actually have the hotels booked already so we can use this information to decide to put a text to tell them to hurray up, or use it to decide that if it's more than 3 minutes since recheckRatesEndTime, then we do another recheack before payment ...etc

I know these all can be added in post hog too, but for now let's just put them in the db directly

2024-12-31 11:50 UTC, Amjad992 commented on postHogUtils.js
> +  distinctId,
what's this distinctId ? 
I see above you are using the bookingId for it, so if that's the case always, then do not take it as parameters and jsut set it directly in the util here 

  postHogClient.capture({
    distinctId: bookingId

2024-12-31 11:50 UTC, Amjad992 commented on postHogUtils.js
> +const postHogClient = new PostHog(process.env.POSTHOG_API_KEY, {
why getting it direclty from process.env.POSTHOG_API_KEY, don't we have config file here?

2024-12-31 11:50 UTC, Amjad992 commented on DraftsModel.js
> +async function handleEventAfterUpdate(doc, next) {
this function looks a bit complex and not understood

either put enough comments, or split it into smaller functions or utils and call them here

it needs to be possible to read it as an english text

for example

2024-12-31 11:50 UTC, Amjad992 commented on DraftsModel.js
> +async function handleEventAfterUpdate(doc, next) {
if (draftisBeingGenerated) {
const {internalBookingId, productTitle, tripCreationStartTime, draftId, stopsObject} = getDraftParams(doc)

const updatedFields = updateDetails.$set || {};

const {cityName, errorCode, checkInMonth} = prepareStopHotelEvent({
      updatedFields,
    });
    
    
if (errorCode) {
      tripCreationFailedEvent({
        distinctId: internalBookingId,
        bookingId: internalBookingId,
        draftId,
        productTitle,
        city: cityName,
        checkInMonth,
        errorCode,
      });
      doc.eventStatus = EVENT_STATUS.error.value;
    }
    
    // Increase providerAmounts
    for (const stop in stops) {
      if (stops[stop]?.hotel?.providerAmount) totalResponses += 1;
    }
    
    const totalStops = Object.keys(stops).length;
    
    const allResponsesReceived = totalResponses === totalStops
    
    
        if (allResponsesReceived) {
             sendCreationSuccessEvents
             
    await doc.save();
  }
}


async function sendCreationSuccessEvents (doc) => {
      doc.eventStatus = EVENT_STATUS.success.value;
      const tripCreationEndTime = new Date(); // End time

      const differenceInSeconds =
        (tripCreationEndTime - tripCreationStartTime) / 1000; // Difference in milliseconds to seconds

      const tripCreationDuration =
        differenceInSeconds >= 60
          ? `${(differenceInSeconds / 60).toFixed(2)} minutes`
          : `${differenceInSeconds.toFixed(2)} seconds`;

      tripCreationDurationEvent({
        distinctId: internalBookingId,
        bookingId: internalBookingId,
        draftId,
        productTitle,
        durationSeconds: tripCreationDuration,
      });

      tripCreationSuccessEvent({
        distinctId: internalBookingId,
        bookingId: internalBookingId,
        draftId,
        productTitle,
      });
    }
}

2024-12-31 11:50 UTC, Amjad992 commented on DraftsModel.js
> +async function handleEventAfterUpdate(doc, next) {
sorry, the above isn't showing properly due to Github code block issue, but you copy and put in file and it will look better

also although this is a sample, but it still look like a bit confusing or ambigous so you might choose to extract more small functions. the above just to show how even renaming some boolean values and extracting some lines outside to a util can help readiability and allow me to know where exactly to focus if I want to fix something

2024-12-31 12:27 UTC, ahmadZahid99 commented on postHogUtils.js
> +  distinctId,
ok

2024-12-31 13:31 UTC, ahmadZahid99 commented on DraftsModel.js
> +    tripCreationStartTime: {
@Amjad992 Ok Amjad bhai I will add that in db but I have one question did I need to add the proper time when each of these actions is performed right now or will it be done at the time when we are sending the event on pre-booking checking and after payment the actual booking

2025-01-01 08:35 UTC, ahmadZahid99 commented on DraftsModel.js
> +}
can you point out where it is used multiple time because i cannot see it any where in this function

2025-01-01 08:51 UTC, ahmadZahid99 commented on DraftsModel.js
> +}
no there is no need because every hook is different and not run consectively

2025-01-01 09:22 UTC, ahmadZahid99 commented on DraftsModel.js
> +async function handleEventAfterUpdate(doc, next) {
done

2025-01-01 09:24 UTC, ahmadZahid99 commented on postHogUtils.js
> +const postHogClient = new PostHog(process.env.POSTHOG_API_KEY, {
no there is no config file in the shared resources but we can used the config of the main app that why i change it here to get the value from the config

2025-01-01 11:04 UTC, ahmadZahid99 commented on utils/draftsUtils.js
> +}
keep it as it is becasue we alway get the doc in the post function

2025-01-01 11:04 UTC, ahmadZahid99 commented on utils/draftsUtils.js
> +}
keep it as it is

2025-01-01 11:05 UTC, ahmadZahid99 commented on utils/draftsUtils.js
> +}
keep it as it is

2025-01-01 11:09 UTC, ahmadZahid99 commented on utils/draftsUtils.js
> +  });
keep it as it is

2025-01-01 12:12 UTC, Amjad992 approved these changes

2025-01-03 15:41 UTC, ahmadZahid99 commented on utils/postHogUtils.js
> +  });
keep it as it is

2025-01-03 15:41 UTC, ahmadZahid99 commented on utils/postHogUtils.js
> +const env = config.get('env');
keep it as it is because they are always there

2025-01-03 15:42 UTC, ahmadZahid99 commented on utils/postHogUtils.js
> +});
keep it as it is

2025-01-03 17:41 UTC, Amjad992 approved these changes

2025-01-06 11:28 UTC, merged